[package]
name = "wage"
version = "0.0.0"
authors = ["Jack Grigg <thestr4d@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
age = { git = "https://github.com/str4d/rage.git", rev = "49bd4611062e3e524f5573c198b800cbe503b259", features = ["async"] }
futures = "0.3"
js-sys = "0.3"
pin-project = "0.4"
secrecy = "0.6"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-streams = { git = "https://github.com/MattiasBuelens/wasm-streams.git", rev = "d0c03d89cdbf7107e401aaf3081c0b02a7a0480f" }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.1", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.2", optional = true }

[dependencies.web-sys]
version = "0.3"
features = [
    "File",
    "ReadableStream",
    "console",
]

[dev-dependencies]
wasm-bindgen-test = "0.2"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[patch.crates-io]
js-sys = { git = "https://github.com/rustwasm/wasm-bindgen.git", rev = "6ba8c6c2ecf4b6969d1118fc263038188db556a2" }
wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen.git", rev = "6ba8c6c2ecf4b6969d1118fc263038188db556a2" }
wasm-bindgen-futures = { git = "https://github.com/rustwasm/wasm-bindgen.git", rev = "6ba8c6c2ecf4b6969d1118fc263038188db556a2" }
wasm-bindgen-macro = { git = "https://github.com/rustwasm/wasm-bindgen.git", rev = "6ba8c6c2ecf4b6969d1118fc263038188db556a2" }
wasm-bindgen-macro-support = { git = "https://github.com/rustwasm/wasm-bindgen.git", rev = "6ba8c6c2ecf4b6969d1118fc263038188db556a2" }
wasm-bindgen-shared = { git = "https://github.com/rustwasm/wasm-bindgen.git", rev = "6ba8c6c2ecf4b6969d1118fc263038188db556a2" }
web-sys = { git = "https://github.com/rustwasm/wasm-bindgen.git", rev = "6ba8c6c2ecf4b6969d1118fc263038188db556a2" }
